server:
  port: 8080


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp"
    username: root
    password: 12345678


api:
  prefix: api/v1
