server:
  port: 8080


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


api:
  prefix: api/v1

jwt:
  expiration: 2592000
  SecretKey: p7vNQ+MZr1rDqKzKZt9JjvT4sByklbl0WXNFGM6Xz9Y=

